In [10]:
#Check your current working directory
import os
print(os.getcwd())

/drive/notebooks/Practise

In [11]:
import os
print(os.listdir())

['Cricket.ipynb', 'odb.csv']

In [12]:
!mamba install pandas

mambajs 0.19.13

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge, conda-forge

Solving environment...
Solving took 3.641 seconds
  Name                          Version                       Build                         Channel
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
+ pandas                        3.0.2                         np22py313h9d9dc1e_0           emscripten-forge
+ python-tzdata                 2026.2                        pyhd8ed1ab_0                  conda-forge
- pip                           25.3                          pyh145f28c_0                  conda-forge

In [13]:
from IPython.display import display
import pandas as pd

df = pd.read_csv("odb.csv")
display(df.head())

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,0,SR Tendulkar (INDIA)^,1989-2012,463.0,452.0,41.0,18426.0,200*,44.83,21368.0,86.23,49.0,96.0,20.0,2016,195
1,1,V Kohli (INDIA) &,2008-2021,254.0,245.0,39.0,12169.0,183,59.07,13061.0,93.17,43.0,62.0,13.0,1140,125
2,2,RT Ponting (AUS/ICC) *,1995-2012,375.0,365.0,39.0,13704.0,164,42.03,17046.0,80.39,30.0,82.0,20.0,1231,162
3,3,RG Sharma (INDIA) %%%,2007-2021,227.0,220.0,32.0,9205.0,264,48.96,10354.0,88.90,29.0,43.0,13.0,832,244
4,4,ST Jayasuriya (Asia/SL),1989-2011,445.0,433.0,18.0,13430.0,189,32.36,14725.0,91.20,28.0,68.0,34.0,1500,270

In [26]:
##select the Required Columns on Dataframe 
from IPython.display import display
import pandas as pd

df = pd.read_csv("odb.csv")
selected_df["Player"] = df["Player"].str.replace(r"[^a-zA-Z\s]", "", regex=True)
##selected_df = df[[ "Span","Mat","Inns","NO","Runs","HS","Ave","BF","SR","100","50","0","4s","6s"] ]  

selected_df = selected_df.copy()

# Step 1: normalize spaces (VERY IMPORTANT)
selected_df["Player"] = selected_df["Player"].str.replace(r"\s+", " ", regex=True).str.strip()

# Step 2: split correctly
selected_df[["Player_Name", "Country"]] = selected_df["Player"].str.rsplit(" ", n=1, expand=True)

display(selected_df.head())

,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s,Player_Name,Country,Player
0,1989-2012,463.0,452.0,41.0,18426.0,200*,44.83,21368.0,86.23,49.0,96.0,20.0,2016,195,SR Tendulkar,INDIA,SR Tendulkar INDIA
1,2008-2021,254.0,245.0,39.0,12169.0,183,59.07,13061.0,93.17,43.0,62.0,13.0,1140,125,V Kohli,INDIA,V Kohli INDIA
2,1995-2012,375.0,365.0,39.0,13704.0,164,42.03,17046.0,80.39,30.0,82.0,20.0,1231,162,RT Ponting,AUSICC,RT Ponting AUSICC
3,2007-2021,227.0,220.0,32.0,9205.0,264,48.96,10354.0,88.90,29.0,43.0,13.0,832,244,RG Sharma,INDIA,RG Sharma INDIA
4,1989-2011,445.0,433.0,18.0,13430.0,189,32.36,14725.0,91.20,28.0,68.0,34.0,1500,270,ST Jayasuriya,AsiaSL,ST Jayasuriya AsiaSL

In [27]:
selected_df = selected_df.copy()

# Split last word as country
selected_df[["Player_Name", "Country"]] = selected_df["Player"].str.rsplit(" ", n=1, expand=True)

display(selected_df.head())

,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s,Player_Name,Country,Player
0,1989-2012,463.0,452.0,41.0,18426.0,200*,44.83,21368.0,86.23,49.0,96.0,20.0,2016,195,SR Tendulkar,INDIA,SR Tendulkar INDIA
1,2008-2021,254.0,245.0,39.0,12169.0,183,59.07,13061.0,93.17,43.0,62.0,13.0,1140,125,V Kohli,INDIA,V Kohli INDIA
2,1995-2012,375.0,365.0,39.0,13704.0,164,42.03,17046.0,80.39,30.0,82.0,20.0,1231,162,RT Ponting,AUSICC,RT Ponting AUSICC
3,2007-2021,227.0,220.0,32.0,9205.0,264,48.96,10354.0,88.90,29.0,43.0,13.0,832,244,RG Sharma,INDIA,RG Sharma INDIA
4,1989-2011,445.0,433.0,18.0,13430.0,189,32.36,14725.0,91.20,28.0,68.0,34.0,1500,270,ST Jayasuriya,AsiaSL,ST Jayasuriya AsiaSL

In [30]:
selected_df = selected_df.drop(columns=["Player"])

In [31]:
display(selected_df.head())

,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s,Player_Name,Country
0,1989-2012,463.0,452.0,41.0,18426.0,200*,44.83,21368.0,86.23,49.0,96.0,20.0,2016,195,SR Tendulkar,INDIA
1,2008-2021,254.0,245.0,39.0,12169.0,183,59.07,13061.0,93.17,43.0,62.0,13.0,1140,125,V Kohli,INDIA
2,1995-2012,375.0,365.0,39.0,13704.0,164,42.03,17046.0,80.39,30.0,82.0,20.0,1231,162,RT Ponting,AUSICC
3,2007-2021,227.0,220.0,32.0,9205.0,264,48.96,10354.0,88.90,29.0,43.0,13.0,832,244,RG Sharma,INDIA
4,1989-2011,445.0,433.0,18.0,13430.0,189,32.36,14725.0,91.20,28.0,68.0,34.0,1500,270,ST Jayasuriya,AsiaSL

In [32]:
#To make the columns in Order Wise
cols = ["Player_Name", "Country"] + [col for col in selected_df.columns if col not in ["Player_Name", "Country"]]

selected_df = selected_df[cols]

display(selected_df.head())

,Player_Name,Country,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,SR Tendulkar,INDIA,1989-2012,463.0,452.0,41.0,18426.0,200*,44.83,21368.0,86.23,49.0,96.0,20.0,2016,195
1,V Kohli,INDIA,2008-2021,254.0,245.0,39.0,12169.0,183,59.07,13061.0,93.17,43.0,62.0,13.0,1140,125
2,RT Ponting,AUSICC,1995-2012,375.0,365.0,39.0,13704.0,164,42.03,17046.0,80.39,30.0,82.0,20.0,1231,162
3,RG Sharma,INDIA,2007-2021,227.0,220.0,32.0,9205.0,264,48.96,10354.0,88.90,29.0,43.0,13.0,832,244
4,ST Jayasuriya,AsiaSL,1989-2011,445.0,433.0,18.0,13430.0,189,32.36,14725.0,91.20,28.0,68.0,34.0,1500,270

In [36]:
selected_df["Country"] = selected_df["Country"].replace({
    "AUSICC": "AUS",
    "AsiaSL": "SL",
    "AfrSA":"SA",
    "AsiaICCSL)":"SL",
    "AfrICCSA":"SA",
    "AsiaPAK":"PAK",
    "AsiaICCINDIA":"INDIA"
})

display(selected_df.head())

,Player_Name,Country,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,SR Tendulkar,INDIA,1989-2012,463.0,452.0,41.0,18426.0,200*,44.83,21368.0,86.23,49.0,96.0,20.0,2016,195
1,V Kohli,INDIA,2008-2021,254.0,245.0,39.0,12169.0,183,59.07,13061.0,93.17,43.0,62.0,13.0,1140,125
2,RT Ponting,AUS,1995-2012,375.0,365.0,39.0,13704.0,164,42.03,17046.0,80.39,30.0,82.0,20.0,1231,162
3,RG Sharma,INDIA,2007-2021,227.0,220.0,32.0,9205.0,264,48.96,10354.0,88.90,29.0,43.0,13.0,832,244
4,ST Jayasuriya,SL,1989-2011,445.0,433.0,18.0,13430.0,189,32.36,14725.0,91.20,28.0,68.0,34.0,1500,270

In [37]:
##To change Country AUS to Australia
selected_df["Country"] = selected_df["Country"].replace({
    "AUS": "Australia",
    "INDIA": "India",
    "SL": "Sri Lanka",
    "SA": "South Africa",
    "PAK": "Pakistan"
})

display(selected_df.head())

,Player_Name,Country,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,SR Tendulkar,India,1989-2012,463.0,452.0,41.0,18426.0,200*,44.83,21368.0,86.23,49.0,96.0,20.0,2016,195
1,V Kohli,India,2008-2021,254.0,245.0,39.0,12169.0,183,59.07,13061.0,93.17,43.0,62.0,13.0,1140,125
2,RT Ponting,Australia,1995-2012,375.0,365.0,39.0,13704.0,164,42.03,17046.0,80.39,30.0,82.0,20.0,1231,162
3,RG Sharma,India,2007-2021,227.0,220.0,32.0,9205.0,264,48.96,10354.0,88.90,29.0,43.0,13.0,832,244
4,ST Jayasuriya,Sri Lanka,1989-2011,445.0,433.0,18.0,13430.0,189,32.36,14725.0,91.20,28.0,68.0,34.0,1500,270